from __future__ import annotations

import importlib.util
from pathlib import Path


def _load_build_module(repo_root: Path):
    module_path = repo_root / "scripts" / "build_submission.py"
    spec = importlib.util.spec_from_file_location("build_submission", module_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_build_submission_creates_whitelist_and_generated_docs(tmp_path, capsys):
    repo_root = Path(__file__).resolve().parents[1]
    module = _load_build_module(repo_root)

    result = module.build_submission(
        repo_root=repo_root,
        dist_root=tmp_path / "dist",
        requirements_text="pydantic==2.0.0\n",
    )

    package_dir = result.package_dir
    assert (package_dir / "chatbot.sh").is_file()
    assert (package_dir / "src" / "classifier.ipynb").is_file()
    assert (package_dir / "src" / "sutra").is_dir()
    assert (package_dir / "src" / "nlp_term").is_dir()
    assert (package_dir / "examples" / "cnu-campus" / "sutra.toml").is_file()
    assert (package_dir / "examples" / "cnu-campus" / "prompts").is_dir()
    assert (package_dir / "examples" / "cnu-campus" / "config").is_dir()
    assert (
        package_dir / "examples" / "cnu-campus" / "data" / "processed" / "knowledge-index.jsonl"
    ).is_file()
    assert (package_dir / "examples" / "cnu-campus" / "data" / "token_config.json").is_file()
    assert (package_dir / "examples" / "cnu-campus" / "evals").is_dir()
    assert (package_dir / "data" / "test_chat.json").is_file()
    assert (package_dir / "data" / "test_realtime.json").is_file()
    assert (package_dir / "pyproject.toml").is_file()

    requirements = (package_dir / "requirements.txt").read_text(encoding="utf-8")
    assert requirements.startswith("# Candidate export generated by uv; confirm during Colab rehearsal.\n")
    assert "pydantic==2.0.0" in requirements

    model_link = (package_dir / "model" / "MODEL_LINK.md").read_text(encoding="utf-8")
    assert "Hugging Face" in model_link
    assert "<DRIVE_LINK_TBD>" in model_link

    readme = (package_dir / "README.md").read_text(encoding="utf-8")
    assert "bash chatbot.sh" in readme
    assert "TF-IDF+LinearSVC" in readme
    assert "BM25 RAG" in readme

    assert not (package_dir / "examples" / "cnu-campus" / "data" / "reports").exists()
    assert not (package_dir / "examples" / "cnu-campus" / "data" / "raw").exists()
    assert not (package_dir / "outputs").exists()
    assert not any("__pycache__" in path.parts for path in package_dir.rglob("*"))
    assert result.zip_path.is_file()
    assert result.file_count > 0
    assert result.total_bytes > 0

    captured = capsys.readouterr()
    assert "WARNING: optional model/classifier.joblib is missing" in captured.out
