from __future__ import annotations

import shutil
import subprocess
import sys
import zipfile
from pathlib import Path
from typing import NamedTuple


PACKAGE_NAME = "Termproject_신해솔"
REQUIREMENTS_NOTE = "# Candidate export generated by uv; confirm during Colab rehearsal."


class BuildResult(NamedTuple):
    package_dir: Path
    zip_path: Path
    file_count: int
    total_bytes: int


def _copy_file(source: Path, target: Path) -> None:
    if not source.is_file():
        raise FileNotFoundError(f"required file is missing: {source}")
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def _ignore_tree(name: str) -> bool:
    return name in {
        "__pycache__",
        ".cache",
        ".ipynb_checkpoints",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".venv",
        "outputs",
    }


def _copy_tree(source: Path, target: Path) -> None:
    if not source.is_dir():
        raise FileNotFoundError(f"required directory is missing: {source}")
    shutil.copytree(
        source,
        target,
        ignore=lambda _dir, names: [name for name in names if _ignore_tree(name)],
    )


def _make_executable(path: Path) -> None:
    try:
        path.chmod(path.stat().st_mode | 0o755)
    except OSError:
        pass


def _generate_requirements(repo_root: Path) -> str:
    command = [
        "uv",
        "export",
        "--no-dev",
        "--extra",
        "rag",
        "--extra",
        "legacy",
        "--extra",
        "ui",
        "--format",
        "requirements-txt",
        "--no-hashes",
    ]
    completed = subprocess.run(
        command,
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return completed.stdout


def _write_requirements(package_dir: Path, requirements_text: str) -> None:
    content = f"{REQUIREMENTS_NOTE}\n{requirements_text.lstrip()}"
    (package_dir / "requirements.txt").write_text(content, encoding="utf-8", newline="\n")


def _write_model_link(package_dir: Path) -> None:
    content = """# Model Link

`chatbot.sh` resolves the configured GGUF path and automatically downloads the Qwen GGUF model from Hugging Face when it is missing.

Google Drive backup link: <DRIVE_LINK_TBD>
"""
    model_dir = package_dir / "model"
    model_dir.mkdir(parents=True, exist_ok=True)
    (model_dir / "MODEL_LINK.md").write_text(content, encoding="utf-8", newline="\n")


def _write_submission_readme(package_dir: Path) -> None:
    content = """# Sutra CNU Campus ChatBot Submission

## How to Run

1. Open `src/classifier.ipynb` in Colab and run all cells. This creates `outputs/cls_output.json`.
2. From the package root, run `bash chatbot.sh` with no arguments. This creates `outputs/chat_output.json` and `outputs/realtime_output.json`.

## Model Download

`chatbot.sh` installs the Python dependencies, resolves the Sutra workspace model path, and downloads the configured Qwen GGUF from Hugging Face when the file is not already present. A Google Drive backup placeholder is documented in `model/MODEL_LINK.md`.

## Output Files

- `outputs/cls_output.json`
- `outputs/chat_output.json`
- `outputs/realtime_output.json`

## System Summary

The submission combines a TF-IDF+LinearSVC classifier notebook, a Sutra BM25 RAG runtime over the CNU campus workspace, registry-backed tool calls for live information paths, and a Chainlit UI entrypoint for interactive use.
"""
    (package_dir / "README.md").write_text(content, encoding="utf-8", newline="\n")


def _copy_cnu_workspace(repo_root: Path, package_dir: Path) -> None:
    source = repo_root / "examples" / "cnu-campus"
    target = package_dir / "examples" / "cnu-campus"
    _copy_file(source / "sutra.toml", target / "sutra.toml")
    _copy_tree(source / "prompts", target / "prompts")
    _copy_tree(source / "config", target / "config")
    _copy_tree(source / "evals", target / "evals")
    _copy_file(source / "data" / "token_config.json", target / "data" / "token_config.json")

    processed_source = source / "data" / "processed"
    processed_target = target / "data" / "processed"
    processed_target.mkdir(parents=True, exist_ok=True)
    for jsonl_path in sorted(processed_source.glob("*.jsonl")):
        _copy_file(jsonl_path, processed_target / jsonl_path.name)


def _copy_optional_classifier(repo_root: Path, package_dir: Path) -> None:
    source = repo_root / "model" / "classifier.joblib"
    if source.is_file():
        _copy_file(source, package_dir / "model" / "classifier.joblib")
        return
    print("WARNING: optional model/classifier.joblib is missing; continuing without it.")


def _iter_files(root: Path):
    for path in sorted(root.rglob("*")):
        if path.is_file():
            yield path


def _create_zip(package_dir: Path, zip_path: Path) -> None:
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in _iter_files(package_dir):
            if any(part in {"__pycache__", ".venv", "outputs"} for part in path.relative_to(package_dir).parts):
                raise RuntimeError(f"excluded path entered package: {path}")
            archive.write(path, path.relative_to(package_dir.parent))


def _print_summary(result: BuildResult) -> None:
    zip_mb = result.zip_path.stat().st_size / (1024 * 1024)
    total_mb = result.total_bytes / (1024 * 1024)
    print(f"Package directory: {result.package_dir}")
    print(f"Zip path: {result.zip_path}")
    print(f"Included files: {result.file_count}")
    print(f"Package size: {total_mb:.2f} MB")
    print(f"Zip size: {zip_mb:.2f} MB")
    print("GGUF included: no")


def build_submission(
    repo_root: Path | None = None,
    dist_root: Path | None = None,
    requirements_text: str | None = None,
) -> BuildResult:
    repo_root = (repo_root or Path(__file__).resolve().parents[1]).resolve()
    dist_root = (dist_root or repo_root / "dist").resolve()
    package_dir = dist_root / PACKAGE_NAME
    zip_path = dist_root / f"{PACKAGE_NAME}.zip"

    if package_dir.exists():
        shutil.rmtree(package_dir)
    if zip_path.exists():
        zip_path.unlink()
    dist_root.mkdir(parents=True, exist_ok=True)

    _copy_file(repo_root / "chatbot.sh", package_dir / "chatbot.sh")
    _make_executable(package_dir / "chatbot.sh")
    _copy_file(repo_root / "src" / "classifier.ipynb", package_dir / "src" / "classifier.ipynb")
    _copy_tree(repo_root / "src" / "sutra", package_dir / "src" / "sutra")
    _copy_tree(repo_root / "src" / "nlp_term", package_dir / "src" / "nlp_term")
    _copy_cnu_workspace(repo_root, package_dir)
    _copy_optional_classifier(repo_root, package_dir)
    _write_model_link(package_dir)
    _copy_file(repo_root / "data" / "test_cls.json", package_dir / "data" / "test_cls.json")
    _copy_file(repo_root / "data" / "test_chat.json", package_dir / "data" / "test_chat.json")
    _copy_file(repo_root / "data" / "test_realtime.json", package_dir / "data" / "test_realtime.json")
    _copy_file(repo_root / "pyproject.toml", package_dir / "pyproject.toml")
    _write_requirements(package_dir, requirements_text or _generate_requirements(repo_root))
    _write_submission_readme(package_dir)

    file_paths = list(_iter_files(package_dir))
    total_bytes = sum(path.stat().st_size for path in file_paths)
    _create_zip(package_dir, zip_path)

    result = BuildResult(
        package_dir=package_dir,
        zip_path=zip_path,
        file_count=len(file_paths),
        total_bytes=total_bytes,
    )
    _print_summary(result)
    return result


def main() -> int:
    try:
        build_submission()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
